name: Build APK

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

    # -----------------------------------
    # checkout repo
    # -----------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    # -----------------------------------
    # node environment
    # -----------------------------------
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # -----------------------------------
    # install dependencies
    # -----------------------------------
    - name: Install dependencies
      run: npm install

    # -----------------------------------
    # install android sdk
    # -----------------------------------
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # -----------------------------------
    # install required sdk packages
    # -----------------------------------
    - name: Install Android packages
      run: |
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-34"
        sdkmanager "build-tools;34.0.0"

    # -----------------------------------
    # setup capacitor android
    # -----------------------------------
    - name: Setup Capacitor
      run: |
        npm install @capacitor/android
        npx cap add android || true
        npx cap sync android

    # -----------------------------------
    # setup java
    # -----------------------------------
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # -----------------------------------
    # build apk
    # -----------------------------------
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    # -----------------------------------
    # rename apk
    # -----------------------------------
    - name: Prepare APK
      run: |
        mkdir release
        cp android/app/build/outputs/apk/debug/app-debug.apk release/countdateapp.apk

    # -----------------------------------
    # delete old releases
    # -----------------------------------
    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # -----------------------------------
    # create release
    # -----------------------------------
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest APK
        files: release/countdateapp.apk
